[package]
name = "webserv_os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlmalloc = "0.2.4"
spin = "0.9.8"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
